# model args
common:
  seed: 42

model:
  encoder:
    path: base_llms/bge-large-en-v1.5
    context_length: 512

  decoder:
    name: Llama-2-7b-chat-hf
    path: base_llms/2_llama/Llama-2-13b-chat-hf
    base:
    context_length: 8192
    generation_config:
      bos_token_id: 1
      eos_token_id: 2
      max_length: 4096
      pad_token_id: 0
      temperature: 0
      top_p: 0.95
      transformers_version: 4.32.0.dev0
      max_new_tokens: 200
      repetition_penalty: 1.15
